import 'dart:math' as math;

import '../../../core/constants/app_enums.dart';
import '../../../data/models/member.dart';
import '../../../data/models/monthly_analytics_snapshot.dart';
import '../../../data/models/project.dart';
import '../../../data/models/report.dart';
import '../../../data/models/task.dart';

/// Builds the premium management report as a complete HTML/CSS document.
///
/// This builder is intended for Flutter Web. It keeps the eight-page report
/// structure supplied by the product design and uses only browser-printable
/// HTML, CSS and inline SVG. The browser can open its normal print preview and
/// save the report as PDF without using a Flutter PDF renderer.
///
/// Base pages:
/// 1. Monthly Company Report
/// 2. Portfolio Delivery Health
/// 3. Task Execution & Throughput
/// 4. Timeline, Dependencies & Milestones
/// 5. Team Capacity & Workload
/// 6. Appraisal & Performance Intelligence
/// 7. Risk, Quality & Notification Operations
/// 8. Management Actions, Audit & Export
///
/// Larger datasets add continuation pages after the fixed eight-page report.
class DynamicReportHtmlBuilder {
  const DynamicReportHtmlBuilder();

  String build({
    required ReportModel report,
    required List<Project> projects,
    required List<ProjectTask> tasks,
    required List<Member> members,
    MonthlyAnalyticsSnapshot? monthlySnapshot,
    int minPages = 8,
  }) {
    final data = _HtmlReportData.from(
      report: report,
      projects: projects,
      tasks: tasks,
      members: members,
      monthlySnapshot: monthlySnapshot,
    );

    final companyName = data.companyName;

    final pageBodies = <String>[
      _pageOne(report, data),
      _pageTwo(data),
      _pageThree(data),
      _pageFour(data),
      _pageFive(data),
      _pageSix(data),
      _pageSeven(report, data),
      _pageEight(report, data),
    ];

    if (data.projects.length > 5) {
      for (final chunk in _chunk(data.projects.skip(5).toList(), 12)) {
        pageBodies.add(_projectContinuation(chunk));
      }
    }
    if (data.tasks.length > 7) {
      for (final chunk in _chunk(data.tasks.skip(7).toList(), 14)) {
        pageBodies.add(_taskContinuation(chunk, data));
      }
    }
    if (data.members.length > 5) {
      for (final chunk in _chunk(data.members.skip(5).toList(), 12)) {
        pageBodies.add(_memberContinuation(chunk, data));
      }
    }

    while (pageBodies.length < math.max(8, minPages)) {
      pageBodies.add(_minimumContinuation(report, pageBodies.length + 1));
    }

    final totalPages = pageBodies.length;
    final pages = <String>[];
    for (var index = 0; index < pageBodies.length; index += 1) {
      pages.add(
        _pageShell(
          pageNumber: index + 1,
          totalPages: totalPages,
          accent: _pageAccent(index),
          companyName: companyName,
          body: pageBodies[index],
        ),
      );
    }

    final title = _escape(
      '${report.reportType}_${report.monthId.isEmpty ? report.period : report.monthId}',
    );

    return '''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>$title</title>
<style>
$_css
</style>
</head>
<body>
<main class="report-document">
${pages.join('\n')}
</main>
</body>
</html>''';
  }

  String _pageOne(ReportModel report, _HtmlReportData data) {
    final visibleProjects = data.projects.take(5).toList(growable: false);
    final companyName = _escape(data.companyName);
    final companyInitial = _escape(data.companyName.isNotEmpty ? data.companyName[0].toUpperCase() : 'C');
    final generatedBy = _escape(data.generatedBy);
    final scope = _escape(data.scopeLabel);

    return '''
<section class="annual-cover">
  <div class="cover-brand">
    <div class="cover-emblem">$companyInitial</div>
    <div>
      <strong>$companyName</strong>
      <span>Enterprise reporting intelligence</span>
    </div>
  </div>

  <div class="cover-copy">
    <div class="cover-kicker">${_escape(data.monthLabel)}</div>
    <h1>Monthly<br><span>Management Report</span></h1>
    <p>${_escape(report.summary.isEmpty ? data.executiveSummary : report.summary)}</p>
    <div class="cover-meta">
      <span>Generated by $generatedBy</span>
      <span>Scope: $scope</span>
    </div>
  </div>

  <div class="cover-visual" aria-hidden="true">
    <div class="cover-image-grid"></div>
    <div class="cover-arc cover-arc-large"></div>
    <div class="cover-arc cover-arc-small"></div>
    <div class="cover-year">${DateTime.now().year}</div>
  </div>
</section>

<div class="cover-summary-band">
  <div>
    <span class="eyebrow">Executive snapshot</span>
    <strong>${data.projectCount} projects · ${data.taskCount} tasks · ${data.memberCount} members</strong>
  </div>
  <div class="cover-score">
    <span>${data.overallCompletion}%</span>
    <small>portfolio health</small>
  </div>
</div>

<div class="metrics metrics-4 editorial-metrics">
  ${_metricCard('P', '${data.projectCount}', 'Projects', 'purple')}
  ${_metricCard('T', '${data.taskCount}', 'Work items', 'blue')}
  ${_metricCard('%', '${data.overallCompletion}%', 'Completion', 'green')}
  ${_metricCard('!', '${data.overdueTasks}', 'Late tasks', 'red')}
</div>

<div class="editorial-columns">
  <div>
    ${_sectionTitle('Executive Summary', 'blue')}
    <p class="body-copy">${_escape(data.executiveSummary)}</p>
    <div class="callout-grid">
      ${_callout('Top Risk', data.topRisk, 'orange')}
      ${_callout('Best Signal', data.bestSignal, 'green')}
      ${_callout('Next Action', data.nextAction, 'blue')}
    </div>
  </div>
  <aside class="editorial-sidebar">
    <span class="eyebrow">Portfolio snapshot</span>
    ${_projectTable(visibleProjects)}
  </aside>
</div>
''';
  }

  String _pageTwo(_HtmlReportData data) {
    final statusCounts = <String, int>{};
    for (final project in data.projects) {
      statusCounts[project.status.label] =
          (statusCounts[project.status.label] ?? 0) + 1;
    }

    return '''
${_titleBlock(
  'Portfolio Delivery Health',
  'Project-level health, schedule confidence, status mix and forecast.',
)}
${_sectionTitle('Status Distribution', 'purple')}
<div class="panel">
  ${_stackedDistribution(statusCounts)}
</div>
${_sectionTitle('Project Health Matrix', 'blue')}
${_projectHealthTable(data.projects.take(7).toList(growable: false))}
${_sectionTitle('Progress & Forecast', 'teal')}
<div class="progress-list">
  ${data.projects.take(6).map((project) => _progressRow(project.name, project.progress, _progressColor(project.progress))).join()}
</div>
${_wideCallout(
  'Portfolio forecast',
  data.portfolioForecast,
  'purple',
)}
''';
  }

  String _pageThree(_HtmlReportData data) {
    final statusCounts = data.taskStatusCounts;
    final priorityCounts = data.taskPriorityCounts;
    final throughput = data.weeklyThroughput;

    return '''
${_titleBlock(
  'Task Execution & Throughput',
  'Task-level KPIs, priority mix, throughput trend and high-value work.',
)}
<div class="metrics metrics-4">
  ${_metricCard('T', '${data.taskCount}', 'Total tasks', 'blue')}
  ${_metricCard('C', '${data.completedTasks}', 'Completed', 'green')}
  ${_metricCard('O', '${data.openTasks}', 'Open', 'orange')}
  ${_metricCard('!', '${data.overdueTasks}', 'Overdue', 'red')}
</div>
${_sectionTitle('Task Status & Priority', 'green')}
<div class="split">
  <div class="panel chart-panel">
    <div class="donut-layout">
      ${_donut(data.taskCompletionRate, 'DONE', 'green')}
      <div class="mini-progress-list">
        ${_compactProgressRows(statusCounts)}
      </div>
    </div>
  </div>
  <div class="panel chart-panel">
    <h3 class="panel-title">Priority mix</h3>
    ${_stackedDistribution(priorityCounts)}
  </div>
</div>
${_sectionTitle('Weekly Throughput', 'blue')}
<div class="panel line-panel">
  ${_lineChart(throughput, const <String>['W1', 'W2', 'W3', 'W4', 'W5', 'W6', 'W7'], '#2563eb')}
</div>
${_sectionTitle('Priority Task Table', 'orange')}
${_taskTable(data.tasks.take(7).toList(growable: false), data)}
''';
  }

  String _pageFour(_HtmlReportData data) {
    final timelineTasks = data.timelineTasks.take(6).toList(growable: false);
    return '''
${_titleBlock(
  'Timeline, Dependencies & Milestones',
  'A graphical schedule view with colored bars, dependency connectors and milestone markers.',
)}
${_sectionTitle('Delivery Timeline', 'cyan')}
<div class="panel gantt-panel">
  ${_gantt(timelineTasks, data)}
</div>
${_sectionTitle('Critical Path & Milestones', 'red')}
${_wideCallout('Critical chain', data.criticalChain, 'red')}
<div class="legend-row">
  ${_legend('In progress', 'blue')}
  ${_legend('Completed', 'green')}
  ${_legend('Review', 'purple')}
  ${_legend('At risk', 'orange')}
  ${_legend('Dependency', 'teal')}
  ${_legend('Today', 'red')}
</div>
''';
  }

  String _pageFive(_HtmlReportData data) {
    final roleCounts = <String, int>{};
    for (final member in data.members) {
      roleCounts[member.role.label] = (roleCounts[member.role.label] ?? 0) + 1;
    }

    return '''
${_titleBlock(
  'Team Capacity & Workload',
  'Workload, capacity, online status and utilization by team member.',
)}
<div class="metrics metrics-4">
  ${_metricCard('M', '${data.memberCount}', 'Members', 'purple')}
  ${_metricCard('O', '${data.onlineMembers}', 'Online now', 'green')}
  ${_metricCard('A', '${data.totalAssignments}', 'Assigned', 'blue')}
  ${_metricCard('%', '${data.averageUtilization}%', 'Avg utilization', 'orange')}
</div>
${_sectionTitle('Role & Capacity Distribution', 'purple')}
<div class="split">
  <div class="panel chart-panel">
    <div class="role-summary">
      <div class="role-count">${roleCounts.length}</div>
      <div class="role-count-label">ROLES</div>
    </div>
    ${_compactProgressRows(roleCounts)}
  </div>
  <div class="panel chart-panel">
    <h3 class="panel-title">Capacity vs utilization</h3>
    ${data.members.take(5).map((member) {
      final utilization = data.memberUtilization(member);
      return _progressRow(member.displayName, utilization, _progressColor(utilization));
    }).join()}
  </div>
</div>
${_sectionTitle('Member Workload', 'blue')}
<div class="member-grid">
  ${data.members.take(5).map((member) => _memberWorkloadCard(member, data)).join()}
</div>
''';
  }

  String _pageSix(_HtmlReportData data) {
    return '''
${_titleBlock(
  'Appraisal & Performance Intelligence',
  'Review coverage, score distribution, performance trend and manager notes.',
)}
<div class="metrics metrics-4">
  ${_metricCard('R', '${data.reviewedMembers}/${data.memberCount}', 'Reviewed', 'orange')}
  ${_metricCard('%', '${data.averageAppraisalScore}%', 'Avg score', 'blue')}
  ${_metricCard('H', '${data.highRatingMembers}', 'High rating', 'green')}
  ${_metricCard('!', '${data.followUpMembers}', 'Needs follow-up', 'red')}
</div>
${_sectionTitle('Performance Score Distribution', 'orange')}
<div class="split">
  <div class="panel chart-panel">
    <div class="donut-layout">
      ${_donut(data.averageAppraisalScore, 'AVERAGE', 'green')}
      <div class="mini-progress-list">
        ${_progressRow('High', data.highRatingPercent, 'green')}
        ${_progressRow('Medium', data.mediumRatingPercent, 'orange')}
        ${_progressRow('Follow-up', data.followUpPercent, 'red')}
      </div>
    </div>
  </div>
  <div class="panel chart-panel">
    <h3 class="panel-title">Six-month score trend</h3>
    ${_lineChart(data.appraisalTrend, const <String>['Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul'], '#f59e0b')}
  </div>
</div>
${_sectionTitle('Member Performance', 'purple')}
${_memberPerformanceTable(data.members.take(7).toList(growable: false), data)}
${_sectionTitle('Manager Insights', 'blue')}
<div class="insight-stack">
  ${_insightRow('Strongest delivery', data.strongestDelivery, 'green')}
  ${_insightRow('Coaching focus', data.coachingFocus, 'orange')}
  ${_insightRow('Review governance', 'Only Admin, PM and Team Lead can modify appraisal values; employees remain view-only.', 'blue')}
</div>
''';
  }

  String _pageSeven(ReportModel report, _HtmlReportData data) {
    final readiness = data.notificationReadiness;
    return '''
${_titleBlock(
  'Risk, Quality & Notification Operations',
  'Operational risks, quality gates and FCM/notification readiness.',
)}
${_sectionTitle('Risk Matrix', 'red')}
<div class="split risk-layout">
  <div class="risk-matrix">
    <div class="axis-label axis-y">Impact</div>
    <div class="axis-label axis-x">Likelihood</div>
    <div class="risk-cell risk-low"></div>
    <div class="risk-cell risk-medium"></div>
    <div class="risk-cell risk-medium"></div>
    <div class="risk-cell risk-high"></div>
    ${_riskChip('DEP', 52, 30, 'orange')}
    ${_riskChip('FCM', 70, 18, 'red')}
    ${_riskChip('PDF', 34, 62, 'blue')}
  </div>
  <div class="panel">
    <h3 class="panel-title">Active Management Risks</h3>
    ${_riskListItem('High', data.topRisk, data.primaryRiskOwner, data.primaryRiskDue, 'red')}
    ${_riskListItem('Medium', 'Timeline dependency mapping', 'Project Manager', data.secondaryRiskDue, 'orange')}
    ${_riskListItem('Low', 'Report HTML pagination and browser print validation', 'Admin', data.tertiaryRiskDue, 'blue')}
  </div>
</div>
${_sectionTitle('FCM / Notification Readiness', 'green')}
<div class="panel readiness-panel">
  ${_readinessRow('Foreground delivery', readiness['foreground'] ?? 0)}
  ${_readinessRow('Background delivery', readiness['background'] ?? 0)}
  ${_readinessRow('Terminated fallback', readiness['terminated'] ?? 0)}
  ${_readinessRow('Accept action logging', readiness['acceptAction'] ?? 0)}
</div>
${_wideCallout(
  'Release gate',
  'Validate the Oracle notification backend, confirm FCM tokens on a real device, test background and terminated actions, and capture the result in the audit log before production release.',
  'red',
)}
''';
  }

  String _pageEight(ReportModel report, _HtmlReportData data) {
    return '''
${_titleBlock(
  'Management Actions, Audit & Export',
  'Recommended actions, report provenance, scope metadata and export controls.',
)}
${_sectionTitle('Recommended Actions', 'teal')}
<div class="action-list">
  ${_action('01', 'Validate Oracle notification backend', 'Deploy and test task-assignment notifications with the production Firebase Admin SDK configuration.', 'blue')}
  ${_action('02', 'Close timeline dependency QA', 'Validate connectors, week/month filters and the selected-task detail panel.', 'purple')}
  ${_action('03', 'Approve report template', 'Lock the eight-page minimum and enable dynamic overflow pages for large datasets.', 'green')}
  ${_action('04', 'Complete appraisal cycle', 'Review remaining scores, manager notes and employee visibility restrictions.', 'orange')}
</div>
${_sectionTitle('Report Audit & Scope', 'blue')}
${_auditTable(report, data)}
${_sectionTitle('Export Assurance', 'purple')}
${_wideCallout(
  'Production behavior',
  'The printable report always contains at least eight meaningful pages. Larger datasets automatically add clean continuation pages with repeated headers, page numbers and safe table breaks. Chrome, Edge and Firefox can print or save the same HTML/CSS layout as PDF.',
  'purple',
)}
''';
  }

  String _projectContinuation(List<Project> projects) {
    return '''
${_titleBlock(
  'Portfolio Continuation',
  'Additional project rows generated from the selected report scope.',
)}
${_sectionTitle('Additional Projects', 'blue')}
${_projectHealthTable(projects)}
''';
  }

  String _taskContinuation(List<ProjectTask> tasks, _HtmlReportData data) {
    return '''
${_titleBlock(
  'Task Execution Continuation',
  'Additional task rows generated from the selected report scope.',
)}
${_sectionTitle('Additional Tasks', 'green')}
${_taskTable(tasks, data)}
''';
  }

  String _memberContinuation(List<Member> members, _HtmlReportData data) {
    return '''
${_titleBlock(
  'Team & Appraisal Continuation',
  'Additional employee workload and appraisal rows.',
)}
${_sectionTitle('Additional Members', 'purple')}
${_memberPerformanceTable(members, data)}
''';
  }

  String _minimumContinuation(ReportModel report, int pageNumber) {
    return '''
${_titleBlock(
  'Report Continuation',
  'Minimum page guarantee page $pageNumber.',
)}
${_wideCallout(
  'Dynamic page behavior',
  'Minimum report length is controlled by minPages. When project, task, member, appraisal, risk or timeline data grows, this page is replaced by live continuation sections.',
  'blue',
)}
<div class="panel key-value-panel">
  ${_keyValue('Report type', report.reportType)}
  ${_keyValue('Period', report.period)}
  ${_keyValue('Status', report.status)}
  ${_keyValue('Project scope', report.projectScope)}
</div>
''';
  }

  String _pageShell({
    required int pageNumber,
    required int totalPages,
    required String accent,
    required String companyName,
    required String body,
  }) {
    final companyInitial = _escape(companyName.isNotEmpty ? companyName[0].toUpperCase() : 'C');
    return '''
<section class="report-page page-$pageNumber" style="--accent:$accent">
  <div class="editorial-sweep" aria-hidden="true"></div>
  <div class="editorial-orb editorial-orb-a" aria-hidden="true"></div>
  <div class="editorial-orb editorial-orb-b" aria-hidden="true"></div>
  <header class="page-header">
    <div class="brand">
      <div class="brand-mark">$companyInitial</div>
      <div class="brand-name">${_escape(companyName)}</div>
    </div>
    <div class="page-number">Page $pageNumber</div>
  </header>
  <div class="page-content">
    $body
  </div>
  <footer class="page-footer">
    <div class="footer-left">
      <span class="footer-accent"></span>
      <span>Generated for ${_escape(companyName)} - confidential internal report</span>
    </div>
    <div>HTML / PDF export&nbsp;&nbsp;|&nbsp;&nbsp;Page $pageNumber of $totalPages</div>
  </footer>
</section>''';
  }

  String _titleBlock(String title, String subtitle) {
    return '''
<div class="title-block">
  <h1>${_escape(title)}</h1>
  <p>${_escape(subtitle)}</p>
</div>''';
  }

  String _sectionTitle(String title, String color) {
    return '''
<div class="section-title">
  <span class="section-bar $color"></span>
  <h2>${_escape(title)}</h2>
</div>''';
  }

  String _metricCard(String icon, String value, String label, String color) {
    return '''
<div class="metric-card">
  <div class="metric-icon $color">${_escape(icon)}</div>
  <div class="metric-copy">
    <div class="metric-value">${_escape(value)}</div>
    <div class="metric-label">${_escape(label)}</div>
  </div>
  <div class="metric-underline $color"></div>
</div>''';
  }

  String _callout(String title, String body, String color) {
    return '''
<div class="callout $color">
  <h3>${_escape(title)}</h3>
  <p>${_escape(body)}</p>
</div>''';
  }

  String _wideCallout(String title, String body, String color) {
    return '''
<div class="wide-callout $color">
  <h3>${_escape(title)}</h3>
  <p>${_escape(body)}</p>
</div>''';
  }

  String _projectTable(List<Project> projects) {
    final rows = projects.isEmpty
        ? '<tr><td colspan="5" class="empty-cell">No project data in this scope.</td></tr>'
        : projects.map((project) {
            return '''
<tr>
  <td>${_escape(project.name)}</td>
  <td>${_escape(project.status.label)}</td>
  <td>${project.progress}%</td>
  <td>${_escape(_projectOwner(project))}</td>
  <td>${_dateShort(project.startDate)} - ${_dateShort(project.dueDate)}</td>
</tr>''';
          }).join();

    return '''
<table class="report-table">
  <thead>
    <tr><th>Project</th><th>Status</th><th>Done</th><th>Owner</th><th>Schedule</th></tr>
  </thead>
  <tbody>$rows</tbody>
</table>''';
  }

  String _projectHealthTable(List<Project> projects) {
    final rows = projects.isEmpty
        ? '<tr><td colspan="6" class="empty-cell">No project data in this scope.</td></tr>'
        : projects.map((project) {
            return '''
<tr>
  <td>${_escape(project.name)}</td>
  <td>${_escape(project.status.label)}</td>
  <td>${project.progress}%</td>
  <td>${_escape(_projectOwner(project))}</td>
  <td>${_dateShort(project.startDate)}</td>
  <td>${_dateShort(project.dueDate)}</td>
</tr>''';
          }).join();

    return '''
<table class="report-table">
  <thead>
    <tr><th>Project</th><th>Status</th><th>Done</th><th>Owner</th><th>Start</th><th>End</th></tr>
  </thead>
  <tbody>$rows</tbody>
</table>''';
  }

  String _taskTable(List<ProjectTask> tasks, _HtmlReportData data) {
    final rows = tasks.isEmpty
        ? '<tr><td colspan="7" class="empty-cell">No task data in this scope.</td></tr>'
        : tasks.map((task) {
            return '''
<tr>
  <td>${_escape(task.title)}</td>
  <td>${_escape(data.projectName(task.projectId))}</td>
  <td>${_escape(data.assigneeNames(task.assignedToIds))}</td>
  <td>${_escape(task.status.label)}</td>
  <td>${_escape(task.priority.label)}</td>
  <td>${data.taskProgress(task)}%</td>
  <td>${_dateShort(task.dueDate)}</td>
</tr>''';
          }).join();

    return '''
<table class="report-table compact">
  <thead>
    <tr><th>Task</th><th>Project</th><th>Owner</th><th>Status</th><th>Priority</th><th>Done</th><th>Due</th></tr>
  </thead>
  <tbody>$rows</tbody>
</table>''';
  }

  String _memberPerformanceTable(List<Member> members, _HtmlReportData data) {
    final rows = members.isEmpty
        ? '<tr><td colspan="6" class="empty-cell">No employee data in this scope.</td></tr>'
        : members.map((member) {
            final assigned = data.assignedTaskCount(member.uid);
            final completed = data.completedTaskCount(member.uid);
            final score = member.appraisalScore;
            return '''
<tr>
  <td>${_escape(member.displayName)}</td>
  <td>${_escape(member.role.label)}</td>
  <td>$assigned</td>
  <td>$completed</td>
  <td>$score%</td>
  <td>${_escape(data.ratingLabel(score))}</td>
</tr>''';
          }).join();

    return '''
<table class="report-table">
  <thead>
    <tr><th>Member</th><th>Role</th><th>Tasks</th><th>Done</th><th>Score</th><th>Rating</th></tr>
  </thead>
  <tbody>$rows</tbody>
</table>''';
  }

  String _auditTable(ReportModel report, _HtmlReportData data) {
    final rows = <List<String>>[
      <String>['Registered company', data.companyName],
      <String>['Report type', report.reportType],
      <String>['Project scope', data.scopeLabel],
      const <String>['Minimum pages', '8'],
      const <String>['Dynamic overflow', 'Enabled - additional pages generated from real data'],
      const <String>['Data sources', 'Projects, tasks, members, timeline, appraisal, workload, notifications'],
      <String>['Generated by', data.generatedBy],
      const <String>['Permission', 'Admin / PM / TL can generate and export'],
      const <String>['Export formats', 'HTML, browser print, Save as PDF, CSV'],
    ];
    return '''
<table class="report-table audit-table">
  <thead><tr><th>Field</th><th>Value</th></tr></thead>
  <tbody>
  ${rows.map((row) => '<tr><td>${_escape(row[0])}</td><td>${_escape(row[1])}</td></tr>').join()}
  </tbody>
</table>''';
  }

  String _stackedDistribution(Map<String, int> values) {
    final entries = values.entries.where((entry) => entry.value > 0).toList();
    final total = entries.fold<int>(0, (sum, entry) => sum + entry.value);
    if (total == 0) {
      return '<div class="empty-chart">No distribution data available.</div>';
    }

    final colors = <String>['green', 'blue', 'purple', 'orange', 'teal', 'red'];
    final segments = <String>[];
    final legends = <String>[];
    for (var index = 0; index < entries.length; index += 1) {
      final entry = entries[index];
      final percent = entry.value * 100 / total;
      final color = colors[index % colors.length];
      segments.add(
        '<span class="stack-segment $color" style="width:${percent.toStringAsFixed(2)}%"></span>',
      );
      legends.add(_legend('${entry.key} (${entry.value})', color));
    }

    return '''
<div class="stacked-bar">${segments.join()}</div>
<div class="legend-row">${legends.join()}</div>''';
  }

  String _compactProgressRows(Map<String, int> values) {
    if (values.isEmpty) return '<div class="empty-chart">No data available.</div>';
    final maxValue = values.values.fold<int>(1, (a, b) => math.max(a, b).toInt());
    return values.entries.take(5).map((entry) {
      final percent = (entry.value * 100 / maxValue).round();
      return _progressRow(entry.key, percent, _categoryColor(entry.key));
    }).join();
  }

  String _progressRow(String label, int value, String color) {
    final safe = value.clamp(0, 100);
    return '''
<div class="progress-row">
  <div class="progress-label">${_escape(label)}</div>
  <div class="progress-track"><span class="progress-fill $color" style="width:$safe%"></span></div>
  <div class="progress-value">$safe%</div>
</div>''';
  }

  String _donut(int value, String label, String color) {
    final safe = value.clamp(0, 100);
    final colorHex = _colorHex(color);
    final remaining = 100 - safe;
    return '''
<div class="donut" style="--donut-color:$colorHex;--donut-value:${safe * 3.6}deg">
  <div class="donut-center">
    <strong>$safe%</strong>
    <span>${_escape(label)}</span>
  </div>
</div>
<span class="sr-only">$safe percent, $remaining percent remaining</span>''';
  }

  String _lineChart(List<int> values, List<String> labels, String color) {
    final safeValues = values.isEmpty ? const <int>[0] : values;
    final count = math.max(2, safeValues.length);
    const width = 720.0;
    const height = 150.0;
    const left = 20.0;
    const right = 20.0;
    const top = 18.0;
    const bottom = 28.0;
    final chartWidth = width - left - right;
    final chartHeight = height - top - bottom;
    final maxValue = math.max(1, safeValues.fold<int>(0, (a, b) => math.max(a, b).toInt())).toInt();

    final points = <String>[];
    final circles = <String>[];
    final labelNodes = <String>[];
    for (var index = 0; index < safeValues.length; index += 1) {
      final x = left + chartWidth * index / (count - 1);
      final y = top + chartHeight * (1 - safeValues[index] / maxValue);
      points.add('${x.toStringAsFixed(1)},${y.toStringAsFixed(1)}');
      circles.add(
        '<circle cx="${x.toStringAsFixed(1)}" cy="${y.toStringAsFixed(1)}" r="5" fill="#fff" stroke="$color" stroke-width="3"/>',
      );
      final label = index < labels.length ? labels[index] : 'P${index + 1}';
      labelNodes.add(
        '<text x="${x.toStringAsFixed(1)}" y="${height - 7}" text-anchor="middle" class="svg-label">${_escape(label)}</text>',
      );
    }

    final grid = <String>[];
    for (var index = 0; index < 4; index += 1) {
      final y = top + chartHeight * index / 3;
      grid.add(
        '<line x1="$left" y1="${y.toStringAsFixed(1)}" x2="${width - right}" y2="${y.toStringAsFixed(1)}" class="svg-grid"/>',
      );
    }

    return '''
<svg class="line-chart" viewBox="0 0 $width $height" role="img" aria-label="Trend line chart">
  ${grid.join()}
  <polyline points="${points.join(' ')}" fill="none" stroke="$color" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>
  ${circles.join()}
  ${labelNodes.join()}
</svg>''';
  }

  String _gantt(List<ProjectTask> tasks, _HtmlReportData data) {
    if (tasks.isEmpty) {
      return '<div class="empty-chart">Add task start dates to generate the delivery timeline.</div>';
    }

    final starts = tasks.map((task) => task.startDate ?? task.createdAt ?? task.dueDate).toList();
    final ends = tasks.map((task) => task.dueDate).toList();
    var minDate = starts.reduce((a, b) => a.isBefore(b) ? a : b);
    var maxDate = ends.reduce((a, b) => a.isAfter(b) ? a : b);
    if (!maxDate.isAfter(minDate)) {
      maxDate = minDate.add(const Duration(days: 1));
    }
    final totalDays = math.max(1, maxDate.difference(minDate).inDays + 1);
    final todayOffset = DateTime.now().difference(minDate).inDays;
    final todayPercent = (todayOffset * 100 / totalDays).clamp(0, 100).toDouble();

    final rows = tasks.asMap().entries.map((entry) {
      final task = entry.value;
      final start = task.startDate ?? task.createdAt ?? task.dueDate;
      final startOffset = start.difference(minDate).inDays;
      final endOffset = task.dueDate.difference(minDate).inDays + 1;
      final left = (startOffset * 100 / totalDays).clamp(0, 100).toDouble();
      final width = ((endOffset - startOffset) * 100 / totalDays).clamp(4, 100 - left).toDouble();
      final color = _taskColor(task);
      final milestone = task.isMilestone
          ? '<span class="milestone $color" style="left:calc(${(left + width).clamp(0, 100).toStringAsFixed(2)}% - 7px)"></span>'
          : '';
      return '''
<div class="gantt-row">
  <div class="gantt-label">${_escape(task.title)}</div>
  <div class="gantt-track">
    <span class="gantt-bar $color" style="left:${left.toStringAsFixed(2)}%;width:${width.toStringAsFixed(2)}%"></span>
    $milestone
  </div>
</div>''';
    }).join();

    return '''
<div class="gantt-head">
  <div>Work item</div>
  <div>${_escape(data.monthLabel)}</div>
</div>
<div class="gantt-body">
  <div class="today-line" style="left:calc(31% + ${todayPercent.toStringAsFixed(2)}% * .69)">
    <span>TODAY</span>
  </div>
  $rows
</div>''';
  }

  String _memberWorkloadCard(Member member, _HtmlReportData data) {
    final assigned = data.assignedTaskCount(member.uid);
    final utilization = data.memberUtilization(member);
    final level = utilization >= 85 ? 'High' : utilization >= 60 ? 'Medium' : 'Low';
    final color = utilization >= 85 ? 'red' : utilization >= 60 ? 'orange' : 'green';
    return '''
<div class="member-card">
  <div class="avatar ${member.isOnline ? 'green' : 'slate'}">${_escape(_initials(member.displayName))}</div>
  <div class="member-main">
    <strong>${_escape(member.displayName)}</strong>
    <span>${_escape(member.role.label)}</span>
    <small>$assigned assigned</small>
  </div>
  <div class="member-util">
    <strong>$utilization% UTIL.</strong>
    <span class="$color-text">${_escape(level)}</span>
  </div>
</div>''';
  }

  String _insightRow(String title, String body, String color) {
    return '''
<div class="insight-row $color">
  <strong>${_escape(title)}</strong>
  <span>${_escape(body)}</span>
</div>''';
  }

  String _readinessRow(String label, int value) {
    final safe = value.clamp(0, 100);
    final color = safe >= 95 ? 'green' : safe >= 80 ? 'orange' : 'red';
    return '''
<div class="readiness-row">
  <span>${_escape(label)}</span>
  <div class="progress-track"><span class="progress-fill $color" style="width:$safe%"></span></div>
  <strong>$safe%</strong>
</div>''';
  }

  String _riskListItem(
    String level,
    String title,
    String owner,
    String due,
    String color,
  ) {
    return '''
<div class="risk-list-item">
  <span class="risk-level $color">${_escape(level)}</span>
  <div>
    <strong>${_escape(title)}</strong>
    <small>Owner: ${_escape(owner)} • Due: ${_escape(due)}</small>
  </div>
</div>''';
  }

  String _riskChip(String label, double left, double top, String color) {
    return '<span class="risk-chip $color" style="left:$left%;top:$top%">${_escape(label)}</span>';
  }

  String _action(String number, String title, String body, String color) {
    return '''
<div class="action-item $color">
  <div class="action-number">$number</div>
  <div>
    <strong>${_escape(title)}</strong>
    <p>${_escape(body)}</p>
  </div>
</div>''';
  }

  String _keyValue(String label, String value) {
    return '''
<div class="key-value">
  <strong>${_escape(label)}</strong>
  <span>${_escape(value)}</span>
</div>''';
  }

  String _legend(String label, String color) {
    return '''
<span class="legend">
  <span class="legend-dot $color"></span>
  ${_escape(label)}
</span>''';
  }

  String _projectOwner(Project project) {
    if (project.managerIds.isEmpty) return 'Unassigned';
    return project.managerIds.first;
  }

  static List<List<T>> _chunk<T>(List<T> items, int size) {
    final output = <List<T>>[];
    for (var index = 0; index < items.length; index += size) {
      output.add(items.sublist(index, math.min(index + size, items.length)));
    }
    return output;
  }

  static String _dateShort(DateTime value) {
    const months = <String>[
      'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
    ];
    return '${value.day.toString().padLeft(2, '0')} ${months[value.month - 1]}';
  }

  static String _initials(String value) {
    final words = value.trim().split(RegExp(r'\s+')).where((word) => word.isNotEmpty).toList();
    if (words.isEmpty) return '?';
    if (words.length == 1) return words.first.substring(0, 1).toUpperCase();
    return '${words.first.substring(0, 1)}${words[1].substring(0, 1)}'.toUpperCase();
  }

  static String _escape(Object? value) {
    return (value ?? '')
        .toString()
        .replaceAll('&', '&amp;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;')
        .replaceAll('"', '&quot;')
        .replaceAll("'", '&#39;');
  }

  static String _pageAccent(int index) {
    const colors = <String>[
      '#2563eb',
      '#7c3aed',
      '#16a34a',
      '#0ea5e9',
      '#7c3aed',
      '#f59e0b',
      '#ef4444',
      '#0f9f91',
    ];
    return colors[index % colors.length];
  }

  static String _categoryColor(String value) {
    final token = value.toLowerCase();
    if (token.contains('complete') || token.contains('done') || token.contains('active')) {
      return 'green';
    }
    if (token.contains('critical') || token.contains('overdue') || token.contains('blocked')) {
      return 'red';
    }
    if (token.contains('high') || token.contains('review')) return 'orange';
    if (token.contains('progress') || token.contains('medium')) return 'blue';
    if (token.contains('low') || token.contains('todo')) return 'teal';
    return 'purple';
  }

  static String _progressColor(int value) {
    if (value >= 85) return 'green';
    if (value >= 60) return 'blue';
    if (value >= 35) return 'orange';
    return 'red';
  }

  static String _taskColor(ProjectTask task) {
    if (task.isOverdue) return 'red';
    if (task.isCompleted) return 'green';
    final status = task.status.value.toLowerCase();
    if (status.contains('review')) return 'purple';
    if (task.priority.index >= 2) return 'orange';
    return 'blue';
  }

  static String _colorHex(String color) {
    switch (color) {
      case 'blue':
        return '#2563eb';
      case 'green':
        return '#16a34a';
      case 'orange':
        return '#f59e0b';
      case 'red':
        return '#ef4444';
      case 'purple':
        return '#7c3aed';
      case 'teal':
        return '#0f9f91';
      case 'cyan':
        return '#0ea5e9';
      default:
        return '#64748b';
    }
  }

  static const String _css = r'''
:root {
  color-scheme: light;
  font-family: Inter, "Segoe UI", Arial, sans-serif;
  --ink: #0f172a;
  --slate: #475569;
  --muted: #64748b;
  --line: #dce4ee;
  --panel: #f8fafc;
  --soft-blue: #eaf2ff;
  --navy: #071a38;
  --blue: #2563eb;
  --purple: #7c3aed;
  --green: #16a34a;
  --orange: #f59e0b;
  --red: #ef4444;
  --teal: #0f9f91;
  --cyan: #0ea5e9;
}
* {
  box-sizing: border-box;
  -webkit-print-color-adjust: exact !important;
  print-color-adjust: exact !important;
}
html, body {
  margin: 0;
  padding: 0;
  background: #e5e7eb;
  color: var(--ink);
}
body {
  min-width: 210mm;
}
.report-document {
  display: flex;
  flex-direction: column;
  gap: 14px;
  align-items: center;
  padding: 14px 0;
}
.report-page {
  --accent: var(--blue);
  position: relative;
  width: 210mm;
  height: 297mm;
  overflow: hidden;
  background: #fff;
  box-shadow: 0 10px 30px rgba(15, 23, 42, .16);
  page-break-after: always;
  break-after: page;
}
.report-page:last-child {
  page-break-after: auto;
  break-after: auto;
}
.page-header {
  height: 23mm;
  padding: 0 10.5mm;
  display: flex;
  align-items: center;
  justify-content: space-between;
  background: var(--navy);
  color: #fff;
}
.brand {
  display: flex;
  align-items: center;
  gap: 4mm;
}
.brand-mark {
  width: 11mm;
  height: 11mm;
  display: grid;
  place-items: center;
  border-radius: 3.2mm;
  background: var(--accent);
  font-size: 13pt;
  font-weight: 800;
}
.brand-name {
  font-size: 11.5pt;
  font-weight: 750;
}
.page-number {
  font-size: 8.8pt;
  color: #dbeafe;
}
.page-content {
  padding: 7.5mm 10.5mm 18mm;
}
.page-footer {
  position: absolute;
  left: 10.5mm;
  right: 10.5mm;
  bottom: 5.5mm;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 5mm;
  padding-top: 3mm;
  border-top: .35mm solid #e5e7eb;
  color: #64748b;
  font-size: 7pt;
}
.footer-left {
  display: flex;
  align-items: center;
  gap: 3mm;
}
.footer-accent {
  width: 12mm;
  height: 1.5mm;
  border-radius: 999px;
  background: var(--accent);
}
.title-block {
  margin-bottom: 7mm;
}
.title-block h1 {
  margin: 0;
  font-size: 24pt;
  line-height: 1.08;
  letter-spacing: -.45pt;
}
.title-block p {
  margin: 2mm 0 0;
  color: var(--muted);
  font-size: 9.2pt;
}
.period-hero {
  min-height: 28mm;
  padding: 5mm 6.5mm;
  margin-bottom: 6mm;
  display: flex;
  align-items: center;
  justify-content: space-between;
  border: .45mm solid #bed3f9;
  border-radius: 6mm;
  background: #eaf2ff;
}
.period-label {
  color: var(--blue);
  font-size: 22pt;
  font-weight: 800;
}
.period-meta {
  margin-top: 3mm;
  color: var(--slate);
  font-size: 8.8pt;
}
.status-chip {
  padding: 2.1mm 4mm;
  border-radius: 999px;
  background: #e8f8ef;
  color: #159447;
  font-size: 7.2pt;
  font-weight: 800;
}
.metrics {
  display: grid;
  gap: 3.4mm;
  margin-bottom: 6mm;
}
.metrics-4 {
  grid-template-columns: repeat(4, 1fr);
}
.metric-card {
  position: relative;
  min-height: 23mm;
  padding: 4.4mm;
  display: flex;
  align-items: center;
  gap: 3.5mm;
  border: .35mm solid #d8e0ea;
  border-radius: 5mm;
  background: #fff;
}
.metric-icon {
  width: 13mm;
  height: 13mm;
  display: grid;
  place-items: center;
  flex: 0 0 auto;
  border-radius: 4mm;
  color: #fff;
  font-size: 10pt;
  font-weight: 800;
}
.metric-value {
  font-size: 16pt;
  font-weight: 800;
}
.metric-label {
  margin-top: 1mm;
  color: var(--muted);
  font-size: 7.5pt;
  font-weight: 600;
}
.metric-underline {
  position: absolute;
  left: 4mm;
  right: 4mm;
  bottom: 1.8mm;
  height: 1mm;
  border-radius: 999px;
}
.section-title {
  margin: 4.7mm 0 3mm;
  display: flex;
  align-items: center;
  gap: 3mm;
}
.section-title h2 {
  margin: 0;
  font-size: 14pt;
}
.section-bar {
  width: 1.7mm;
  height: 7mm;
  border-radius: 999px;
}
.body-copy {
  margin: 0 0 3.5mm;
  color: var(--slate);
  font-size: 8.8pt;
  line-height: 1.45;
}
.callout-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 3.4mm;
}
.callout,
.wide-callout {
  border: .35mm solid #dbe2ea;
  border-radius: 5mm;
}
.callout {
  min-height: 29mm;
  padding: 4.5mm;
}
.callout h3,
.wide-callout h3 {
  margin: 0 0 2.3mm;
  font-size: 9.4pt;
}
.callout p,
.wide-callout p {
  margin: 0;
  color: var(--slate);
  font-size: 7.6pt;
  line-height: 1.42;
}
.wide-callout {
  padding: 5.5mm 6mm;
}
.panel {
  padding: 5mm;
  border: .35mm solid #dbe2ea;
  border-radius: 5.5mm;
  background: #fff;
}
.chart-panel {
  min-height: 39mm;
}
.panel-title {
  margin: 0 0 4mm;
  font-size: 11pt;
}
.split {
  display: grid;
  grid-template-columns: 1fr 1.08fr;
  gap: 4mm;
}
.report-table {
  width: 100%;
  border-collapse: collapse;
  table-layout: fixed;
  border: .35mm solid #d6dee8;
  font-size: 7.4pt;
}
.report-table th {
  padding: 2.8mm 2.2mm;
  text-align: left;
  background: #eaf2ff;
  color: var(--ink);
  font-weight: 800;
}
.report-table td {
  padding: 2.35mm 2.2mm;
  color: var(--slate);
  border-top: .25mm solid #e4e9ef;
  overflow-wrap: anywhere;
}
.report-table tbody tr:nth-child(even) {
  background: #f8fafc;
}
.report-table.compact {
  font-size: 6.7pt;
}
.empty-cell {
  text-align: center;
  padding: 8mm !important;
  color: var(--muted) !important;
}
.page-one-health {
  position: absolute;
  right: 12mm;
  bottom: 23mm;
  text-align: center;
}
.chart-caption {
  margin-top: 2mm;
  color: var(--muted);
  font-size: 7.4pt;
  font-weight: 650;
}
.stacked-bar {
  width: 100%;
  height: 7mm;
  display: flex;
  overflow: hidden;
  border-radius: 999px;
  background: #eef2f7;
}
.stack-segment {
  height: 100%;
}
.legend-row {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 4mm 7mm;
  margin-top: 4mm;
  color: var(--muted);
  font-size: 7.2pt;
}
.legend {
  display: inline-flex;
  align-items: center;
  gap: 2mm;
}
.legend-dot {
  width: 2.4mm;
  height: 2.4mm;
  border-radius: 50%;
}
.progress-list {
  display: grid;
  gap: 3.1mm;
}
.progress-row {
  display: grid;
  grid-template-columns: 38mm 1fr 11mm;
  align-items: center;
  gap: 3mm;
  margin-bottom: 2.6mm;
}
.progress-label {
  overflow: hidden;
  color: var(--ink);
  font-size: 7.7pt;
  font-weight: 650;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.progress-track {
  height: 3.2mm;
  overflow: hidden;
  border-radius: 999px;
  background: #edf2f7;
}
.progress-fill {
  display: block;
  height: 100%;
  border-radius: 999px;
}
.progress-value {
  text-align: right;
  color: var(--slate);
  font-size: 7.4pt;
  font-weight: 750;
}
.donut-layout {
  display: flex;
  align-items: center;
  gap: 8mm;
}
.donut {
  --donut-color: var(--green);
  --donut-value: 0deg;
  width: 31mm;
  height: 31mm;
  display: grid;
  place-items: center;
  flex: 0 0 auto;
  border-radius: 50%;
  background: conic-gradient(var(--donut-color) 0 var(--donut-value), #edf2f7 var(--donut-value) 360deg);
}
.donut-center {
  width: 21mm;
  height: 21mm;
  display: grid;
  place-content: center;
  text-align: center;
  border-radius: 50%;
  background: #fff;
}
.donut-center strong {
  font-size: 15pt;
}
.donut-center span {
  margin-top: 1mm;
  color: var(--muted);
  font-size: 6.5pt;
  font-weight: 700;
}
.mini-progress-list {
  flex: 1;
}
.line-panel {
  height: 39mm;
  padding: 2mm 4mm 1mm;
}
.line-chart {
  width: 100%;
  height: 100%;
}
.svg-grid {
  stroke: #e6ebf0;
  stroke-width: 1;
}
.svg-label {
  fill: #64748b;
  font: 11px "Segoe UI", Arial, sans-serif;
}
.gantt-panel {
  padding: 5mm 4mm 4mm;
}
.gantt-head,
.gantt-row {
  display: grid;
  grid-template-columns: 31% 69%;
  align-items: center;
}
.gantt-head {
  margin-bottom: 4mm;
  color: var(--ink);
  font-size: 7.5pt;
  font-weight: 800;
}
.gantt-body {
  position: relative;
}
.gantt-row {
  min-height: 14mm;
}
.gantt-label {
  padding-right: 4mm;
  color: var(--ink);
  font-size: 7.5pt;
  font-weight: 650;
}
.gantt-track {
  position: relative;
  height: 6mm;
  overflow: visible;
  border-radius: 999px;
  background:
    repeating-linear-gradient(
      to right,
      #eef2f6 0,
      #eef2f6 calc(7.14% - .25mm),
      #dbe3eb calc(7.14% - .25mm),
      #dbe3eb 7.14%
    );
}
.gantt-bar {
  position: absolute;
  top: 0;
  height: 6mm;
  min-width: 5mm;
  border-radius: 999px;
}
.milestone {
  position: absolute;
  top: -1.2mm;
  width: 7mm;
  height: 7mm;
  transform: rotate(45deg);
}
.today-line {
  position: absolute;
  top: -7mm;
  bottom: 0;
  width: .45mm;
  z-index: 4;
  background: var(--red);
}
.today-line span {
  position: absolute;
  top: -5mm;
  left: -8mm;
  padding: 1mm 2.5mm;
  border-radius: 999px;
  background: #fff0f1;
  color: var(--red);
  font-size: 6.5pt;
  font-weight: 800;
  white-space: nowrap;
}
.role-summary {
  display: flex;
  align-items: baseline;
  gap: 2mm;
  margin-bottom: 4mm;
}
.role-count {
  font-size: 25pt;
  font-weight: 850;
}
.role-count-label {
  color: var(--muted);
  font-size: 7pt;
  font-weight: 750;
}
.member-grid {
  display: grid;
  gap: 2.6mm;
}
.member-card {
  min-height: 18mm;
  padding: 3mm 4mm;
  display: flex;
  align-items: center;
  gap: 3.5mm;
  border: .35mm solid #dbe2ea;
  border-radius: 4.5mm;
  background: #fff;
}
.avatar {
  width: 10mm;
  height: 10mm;
  display: grid;
  place-items: center;
  flex: 0 0 auto;
  border-radius: 3mm;
  color: #fff;
  font-size: 7.5pt;
  font-weight: 800;
}
.member-main {
  min-width: 0;
  display: flex;
  flex: 1;
  flex-direction: column;
}
.member-main strong {
  font-size: 8.5pt;
}
.member-main span,
.member-main small {
  color: var(--muted);
  font-size: 6.9pt;
}
.member-util {
  text-align: right;
  font-size: 7.2pt;
}
.member-util span {
  display: block;
  margin-top: 1mm;
}
.insight-stack {
  display: grid;
  gap: 3mm;
}
.insight-row {
  min-height: 16mm;
  padding: 3.8mm 5mm;
  display: grid;
  grid-template-columns: 40mm 1fr;
  align-items: center;
  gap: 5mm;
  border: .35mm solid #dbe2ea;
  border-radius: 4.5mm;
}
.insight-row strong {
  font-size: 8.2pt;
}
.insight-row span {
  color: var(--slate);
  font-size: 7.5pt;
}
.risk-layout {
  grid-template-columns: .9fr 1.1fr;
}
.risk-matrix {
  position: relative;
  min-height: 66mm;
  display: grid;
  grid-template-columns: 1fr 1fr;
  grid-template-rows: 1fr 1fr;
  border: .35mm solid #dbe2ea;
  border-radius: 5mm;
  overflow: hidden;
}
.risk-cell {
  border: .2mm solid rgba(255,255,255,.7);
}
.risk-low {
  background: #eaf8ef;
}
.risk-medium {
  background: #fff4d8;
}
.risk-high {
  background: #ffe6e9;
}
.risk-chip {
  position: absolute;
  z-index: 4;
  min-width: 9mm;
  padding: 1.5mm 2mm;
  transform: translate(-50%, -50%);
  border-radius: 999px;
  color: #fff;
  font-size: 6.5pt;
  font-weight: 800;
  text-align: center;
}
.axis-label {
  position: absolute;
  z-index: 5;
  color: var(--muted);
  font-size: 6.5pt;
  font-weight: 750;
}
.axis-y {
  left: 2mm;
  top: 2mm;
}
.axis-x {
  right: 2mm;
  bottom: 2mm;
}
.risk-list-item {
  display: flex;
  align-items: flex-start;
  gap: 3mm;
  margin-bottom: 4mm;
}
.risk-level {
  min-width: 15mm;
  padding: 1.3mm 2.2mm;
  border-radius: 999px;
  color: #fff;
  font-size: 6.5pt;
  font-weight: 800;
  text-align: center;
}
.risk-list-item strong {
  display: block;
  font-size: 8.2pt;
}
.risk-list-item small {
  display: block;
  margin-top: 1mm;
  color: var(--muted);
  font-size: 6.8pt;
}
.readiness-panel {
  display: grid;
  gap: 3mm;
}
.readiness-row {
  display: grid;
  grid-template-columns: 47mm 1fr 12mm;
  align-items: center;
  gap: 3mm;
  color: var(--slate);
  font-size: 7.5pt;
}
.readiness-row strong {
  text-align: right;
}
.action-list {
  display: grid;
  gap: 4mm;
}
.action-item {
  min-height: 20mm;
  padding: 4mm 5mm;
  display: flex;
  align-items: center;
  gap: 5mm;
  border: .35mm solid #dbe2ea;
  border-radius: 5mm;
}
.action-number {
  width: 13mm;
  height: 13mm;
  display: grid;
  place-items: center;
  flex: 0 0 auto;
  border-radius: 3.4mm;
  color: #fff;
  font-size: 8pt;
  font-weight: 800;
}
.action-item strong {
  font-size: 9pt;
}
.action-item p {
  margin: 1.5mm 0 0;
  color: var(--slate);
  font-size: 7.3pt;
}
.key-value-panel {
  margin-top: 5mm;
}
.key-value {
  display: grid;
  grid-template-columns: 42mm 1fr;
  gap: 5mm;
  padding: 3mm 0;
  border-bottom: .25mm solid #e4e9ef;
  font-size: 8pt;
}
.key-value span {
  color: var(--slate);
}
.empty-chart {
  padding: 10mm;
  color: var(--muted);
  font-size: 8pt;
  text-align: center;
}
.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  overflow: hidden;
  clip: rect(0,0,0,0);
}
.blue { background-color: var(--blue) !important; }
.purple { background-color: var(--purple) !important; }
.green { background-color: var(--green) !important; }
.orange { background-color: var(--orange) !important; }
.red { background-color: var(--red) !important; }
.teal { background-color: var(--teal) !important; }
.cyan { background-color: var(--cyan) !important; }
.slate { background-color: var(--slate) !important; }
.callout.blue, .wide-callout.blue, .insight-row.blue { background: #eaf2ff !important; }
.callout.purple, .wide-callout.purple, .insight-row.purple { background: #f2eaff !important; }
.callout.green, .wide-callout.green, .insight-row.green { background: #eaf8ef !important; }
.callout.orange, .wide-callout.orange, .insight-row.orange { background: #fff4d8 !important; }
.callout.red, .wide-callout.red, .insight-row.red { background: #ffecee !important; }
.callout.teal, .wide-callout.teal, .insight-row.teal { background: #e7f8f5 !important; }
.callout.blue h3, .wide-callout.blue h3 { color: var(--blue); }
.callout.purple h3, .wide-callout.purple h3 { color: var(--purple); }
.callout.green h3, .wide-callout.green h3 { color: var(--green); }
.callout.orange h3, .wide-callout.orange h3 { color: #d78b00; }
.callout.red h3, .wide-callout.red h3 { color: var(--red); }
.callout.teal h3, .wide-callout.teal h3 { color: var(--teal); }
.orange-text { color: #d68a00; }
.green-text { color: var(--green); }
.red-text { color: var(--red); }
.blue-text { color: var(--blue); }
.purple-text { color: var(--purple); }
.teal-text { color: var(--teal); }
.action-item.blue { background: #eaf2ff !important; }
.action-item.purple { background: #f2eaff !important; }
.action-item.green { background: #eaf8ef !important; }
.action-item.orange { background: #fff4d8 !important; }
.action-item.red { background: #ffecee !important; }
.action-item.blue .action-number { background: var(--blue); }
.action-item.purple .action-number { background: var(--purple); }
.action-item.green .action-number { background: var(--green); }
.action-item.orange .action-number { background: var(--orange); }
.action-item.red .action-number { background: var(--red); }
@media screen {
  .report-page {
    transform-origin: top center;
  }
}
@media print {
  @page {
    size: A4 portrait;
    margin: 0;
  }
  html, body {
    width: 210mm;
    min-width: 210mm;
    margin: 0 !important;
    padding: 0 !important;
    background: #fff !important;
  }
  .report-document {
    display: block;
    padding: 0;
  }
  .report-page {
    margin: 0;
    box-shadow: none;
  }
}

/* --------------------------------------------------------------------------
   V284 HIGH-END ANNUAL REPORT THEME
   Editorial cobalt/white art direction inspired by premium corporate reports.
   -------------------------------------------------------------------------- */
:root {
  --navy: #071733;
  --royal: #123f9b;
  --cobalt: #1749b3;
  --sky: #a8c7ef;
  --mist: #eef4fb;
  --paper: #ffffff;
}
.report-page {
  isolation: isolate;
  background:
    linear-gradient(180deg, rgba(241,246,252,.52), rgba(255,255,255,0) 34mm),
    #fff;
}
.report-page::before {
  content: "";
  position: absolute;
  inset: 0;
  z-index: -3;
  background:
    linear-gradient(90deg, rgba(23,73,179,.025) 1px, transparent 1px),
    linear-gradient(rgba(23,73,179,.025) 1px, transparent 1px);
  background-size: 9mm 9mm;
  pointer-events: none;
}
.editorial-sweep {
  position: absolute;
  right: -36mm;
  top: -29mm;
  z-index: -1;
  width: 110mm;
  height: 96mm;
  border-radius: 50%;
  background: linear-gradient(145deg, #0a2b72 0%, #1649b3 58%, #2c65cf 100%);
  transform: rotate(-14deg);
  opacity: .98;
}
.editorial-sweep::after {
  content: "";
  position: absolute;
  left: -18mm;
  bottom: -7mm;
  width: 61mm;
  height: 51mm;
  border: 13mm solid rgba(180,206,239,.8);
  border-left-color: transparent;
  border-bottom-color: transparent;
  border-radius: 50%;
  transform: rotate(23deg);
}
.editorial-orb {
  position: absolute;
  z-index: -2;
  border-radius: 50%;
  pointer-events: none;
}
.editorial-orb-a {
  left: -21mm;
  bottom: 16mm;
  width: 50mm;
  height: 50mm;
  background: rgba(167,197,235,.18);
}
.editorial-orb-b {
  right: 10mm;
  bottom: 28mm;
  width: 25mm;
  height: 25mm;
  border: 7mm solid rgba(23,73,179,.08);
}
.page-header {
  position: relative;
  z-index: 2;
  height: 20mm;
  padding: 0 10.5mm;
  background: transparent;
  color: var(--navy);
}
.brand-mark {
  background: var(--accent);
  box-shadow: 0 2.5mm 7mm rgba(13,44,99,.18);
}
.brand-name {
  color: var(--navy);
  letter-spacing: -.1pt;
}
.page-number {
  color: #dbe7fb;
  background: rgba(7,23,51,.38);
  border: .3mm solid rgba(255,255,255,.28);
  border-radius: 999px;
  padding: 1.8mm 3.2mm;
}
.page-content {
  padding-top: 4mm;
}
.title-block {
  max-width: 138mm;
}
.title-block h1 {
  color: var(--navy);
  font-size: 25pt;
  letter-spacing: -.8pt;
}
.title-block p {
  max-width: 125mm;
  line-height: 1.55;
}
.section-title h2 {
  font-size: 13.2pt;
  letter-spacing: -.15pt;
}
.section-bar {
  width: 1.25mm;
  height: 8mm;
}
.panel,
.metric-card,
.callout,
.wide-callout,
.member-card,
.action-item,
.report-table {
  box-shadow: 0 2.5mm 8mm rgba(15,34,70,.055);
}
.metric-card {
  border-color: rgba(144,167,196,.45);
}
.metric-icon {
  border-radius: 50%;
}
.report-table {
  border-radius: 3mm;
  overflow: hidden;
}
.report-table th {
  background: linear-gradient(90deg, #eef4ff, #f7faff);
}
.report-table tbody tr:nth-child(even) {
  background: #f7f9fc;
}
.page-footer {
  color: #60708b;
}
.footer-accent {
  background: linear-gradient(90deg, var(--accent), #8db5ee);
}

/* Premium cover page */
.page-1 .page-header,
.page-1 .editorial-sweep,
.page-1 .editorial-orb {
  display: none;
}
.page-1 .page-content {
  padding: 0 0 17mm;
}
.page-1 .page-footer {
  left: 9mm;
  right: 9mm;
}
.annual-cover {
  position: relative;
  min-height: 116mm;
  overflow: hidden;
  padding: 10mm 11mm 12mm;
  color: #fff;
  background:
    linear-gradient(90deg, rgba(5,22,53,.97) 0 41%, rgba(12,47,116,.85) 41% 100%),
    linear-gradient(135deg, #071733, #1b55bd);
}
.annual-cover::after {
  content: "";
  position: absolute;
  left: -24mm;
  bottom: -49mm;
  width: 137mm;
  height: 110mm;
  border: 27mm solid #1649b3;
  border-right-color: transparent;
  border-bottom-color: transparent;
  border-radius: 50%;
  transform: rotate(-10deg);
  opacity: .98;
}
.cover-brand {
  position: relative;
  z-index: 6;
  display: flex;
  align-items: center;
  gap: 3mm;
}
.cover-emblem {
  width: 9mm;
  height: 9mm;
  display: grid;
  place-items: center;
  border: .45mm solid rgba(255,255,255,.78);
  border-radius: 2mm;
  font-weight: 850;
}
.cover-brand strong,
.cover-brand span {
  display: block;
}
.cover-brand strong {
  font-size: 7.4pt;
  letter-spacing: .2pt;
}
.cover-brand span {
  margin-top: .5mm;
  color: #bfd2ef;
  font-size: 5.7pt;
}
.cover-copy {
  position: relative;
  z-index: 7;
  width: 91mm;
  margin-top: 18mm;
}
.cover-kicker {
  margin-bottom: 4mm;
  color: #c6d9f4;
  font-size: 12pt;
  font-weight: 350;
}
.cover-copy h1 {
  margin: 0;
  font-size: 29pt;
  line-height: 1.02;
  letter-spacing: -1.1pt;
}
.cover-copy h1 span {
  font-weight: 350;
}
.cover-copy p {
  width: 74mm;
  margin: 6mm 0 0;
  color: #d7e3f6;
  font-size: 7.6pt;
  line-height: 1.55;
}
.cover-meta {
  display: flex;
  gap: 7mm;
  margin-top: 8mm;
  color: #b8ccec;
  font-size: 6.4pt;
}
.cover-visual {
  position: absolute;
  inset: 0 0 0 91mm;
  z-index: 3;
  overflow: hidden;
}
.cover-image-grid {
  position: absolute;
  inset: 0;
  opacity: .78;
  background:
    linear-gradient(90deg, rgba(7,23,51,.12), rgba(255,255,255,.08)),
    repeating-linear-gradient(90deg, rgba(255,255,255,.16) 0 1px, transparent 1px 8mm),
    repeating-linear-gradient(0deg, rgba(255,255,255,.11) 0 1px, transparent 1px 6mm),
    linear-gradient(135deg, #9eb6d4, #36598c 44%, #102a58 100%);
}
.cover-image-grid::before {
  content: "";
  position: absolute;
  left: 10mm;
  right: 8mm;
  bottom: 13mm;
  height: 49mm;
  background:
    linear-gradient(90deg,
      transparent 0 5%,
      rgba(255,255,255,.72) 5% 8%,
      transparent 8% 18%,
      rgba(255,255,255,.58) 18% 21%,
      transparent 21% 33%,
      rgba(255,255,255,.48) 33% 36%,
      transparent 36% 100%),
    linear-gradient(180deg, rgba(238,244,251,.88), rgba(90,119,157,.58));
  clip-path: polygon(0 28%, 18% 9%, 18% 21%, 42% 3%, 42% 19%, 71% 0, 71% 17%, 100% 5%, 100% 100%, 0 100%);
}
.cover-image-grid::after {
  content: "";
  position: absolute;
  left: 0;
  right: 0;
  bottom: 8mm;
  height: 20mm;
  background:
    repeating-linear-gradient(90deg, #dce6f3 0 3mm, #8ba5c6 3mm 3.5mm),
    linear-gradient(#c7d6e8, #8fa8c6);
  opacity: .82;
  transform: perspective(80mm) rotateX(58deg);
  transform-origin: bottom;
}
.cover-arc {
  position: absolute;
  border-radius: 50%;
  border-style: solid;
}
.cover-arc-large {
  right: -42mm;
  top: -29mm;
  width: 110mm;
  height: 110mm;
  border-width: 24mm;
  border-color: #1649b3;
}
.cover-arc-small {
  right: 2mm;
  top: 6mm;
  width: 38mm;
  height: 38mm;
  border-width: 9mm;
  border-color: rgba(180,205,239,.76);
}
.cover-year {
  position: absolute;
  right: 8mm;
  top: 11mm;
  z-index: 8;
  color: rgba(255,255,255,.9);
  font-size: 10pt;
  font-weight: 500;
  letter-spacing: .5pt;
}
.cover-summary-band {
  margin: 6mm 10.5mm 4mm;
  padding: 4mm 5mm;
  display: flex;
  align-items: center;
  justify-content: space-between;
  border-left: 1.4mm solid #1749b3;
  background: linear-gradient(90deg, #edf4ff, #fff);
}
.cover-summary-band strong,
.cover-summary-band span,
.cover-summary-band small {
  display: block;
}
.eyebrow {
  color: #1749b3;
  font-size: 6.2pt;
  font-weight: 850;
  letter-spacing: .75pt;
  text-transform: uppercase;
}
.cover-summary-band strong {
  margin-top: 1mm;
  font-size: 9.4pt;
}
.cover-score {
  text-align: right;
}
.cover-score span {
  color: #1749b3;
  font-size: 19pt;
  font-weight: 850;
}
.cover-score small {
  color: #65738b;
  font-size: 6.3pt;
}
.page-1 .editorial-metrics,
.page-1 .editorial-columns {
  margin-left: 10.5mm;
  margin-right: 10.5mm;
}
.editorial-columns {
  display: grid;
  grid-template-columns: 1.04fr .96fr;
  gap: 4mm;
  align-items: start;
}
.editorial-sidebar {
  padding: 4.5mm;
  border-radius: 4mm;
  background: #f4f7fb;
}
.editorial-sidebar .report-table {
  margin-top: 2.5mm;
  font-size: 6.4pt;
}
.editorial-sidebar .report-table th,
.editorial-sidebar .report-table td {
  padding: 1.8mm 1.7mm;
}
.page-1 .callout-grid {
  grid-template-columns: 1fr;
  gap: 2.2mm;
}
.page-1 .callout {
  min-height: auto;
  padding: 3mm 3.6mm;
}
.page-1 .callout h3 {
  margin-bottom: 1.2mm;
}
.page-1 .callout p {
  font-size: 6.8pt;
}
@media print {
  .report-page {
    box-shadow: none !important;
  }
}
''';
}

class _HtmlReportData {
  const _HtmlReportData({
    required this.report,
    required this.projects,
    required this.tasks,
    required this.members,
    required this.companyName,
    required this.generatedBy,
    required this.monthLabel,
    required this.scopeLabel,
    required this.projectCount,
    required this.taskCount,
    required this.memberCount,
    required this.completedTasks,
    required this.overdueTasks,
    required this.overallCompletion,
    required this.onlineMembers,
    required this.totalAssignments,
    required this.averageUtilization,
    required this.reviewedMembers,
    required this.averageAppraisalScore,
    required this.highRatingMembers,
    required this.followUpMembers,
    required this.executiveSummary,
    required this.topRisk,
    required this.bestSignal,
    required this.nextAction,
    required this.portfolioForecast,
    required this.criticalChain,
    required this.strongestDelivery,
    required this.coachingFocus,
    required this.taskStatusCounts,
    required this.taskPriorityCounts,
    required this.weeklyThroughput,
    required this.appraisalTrend,
    required this.notificationReadiness,
  });

  final ReportModel report;
  final List<Project> projects;
  final List<ProjectTask> tasks;
  final List<Member> members;
  final String companyName;
  final String generatedBy;
  final String monthLabel;
  final String scopeLabel;
  final int projectCount;
  final int taskCount;
  final int memberCount;
  final int completedTasks;
  final int overdueTasks;
  final int overallCompletion;
  final int onlineMembers;
  final int totalAssignments;
  final int averageUtilization;
  final int reviewedMembers;
  final int averageAppraisalScore;
  final int highRatingMembers;
  final int followUpMembers;
  final String executiveSummary;
  final String topRisk;
  final String bestSignal;
  final String nextAction;
  final String portfolioForecast;
  final String criticalChain;
  final String strongestDelivery;
  final String coachingFocus;
  final Map<String, int> taskStatusCounts;
  final Map<String, int> taskPriorityCounts;
  final List<int> weeklyThroughput;
  final List<int> appraisalTrend;
  final Map<String, int> notificationReadiness;

  int get openTasks => math.max(0, taskCount - completedTasks);
  int get taskCompletionRate => taskCount == 0 ? 0 : (completedTasks * 100 / taskCount).round();

  List<ProjectTask> get timelineTasks {
    final output = tasks.where((task) => task.startDate != null || task.createdAt != null).toList();
    output.sort((a, b) {
      final aStart = a.startDate ?? a.createdAt ?? a.dueDate;
      final bStart = b.startDate ?? b.createdAt ?? b.dueDate;
      return aStart.compareTo(bStart);
    });
    return output;
  }

  int get highRatingPercent =>
      reviewedMembers == 0 ? 0 : (highRatingMembers * 100 / reviewedMembers).round();

  int get followUpPercent =>
      reviewedMembers == 0 ? 0 : (followUpMembers * 100 / reviewedMembers).round();

  int get mediumRatingPercent =>
      (100 - highRatingPercent - followUpPercent).clamp(0, 100).toInt();

  String get primaryRiskOwner => tasks.isEmpty ? 'Team Lead' : assigneeNames(tasks.first.assignedToIds);
  String get primaryRiskDue => tasks.isEmpty ? '-' : _short(tasks.first.dueDate);
  String get secondaryRiskDue => tasks.length < 2 ? '-' : _short(tasks[1].dueDate);
  String get tertiaryRiskDue => tasks.length < 3 ? '-' : _short(tasks[2].dueDate);

  static _HtmlReportData from({
    required ReportModel report,
    required List<Project> projects,
    required List<ProjectTask> tasks,
    required List<Member> members,
    required MonthlyAnalyticsSnapshot? monthlySnapshot,
  }) {
    final companyName = report.metrics['companyName']?.toString().trim().isNotEmpty == true
        ? report.metrics['companyName'].toString().trim()
        : 'Company Workspace';

    final namesByUid = <String, String>{
      for (final member in members) member.uid: member.displayName,
    };

    final rawGeneratedBy = report.metrics['generatedByName']?.toString().trim() ??
        report.generatedBy?.trim() ??
        '';
    final generatedBy = namesByUid[rawGeneratedBy] ??
        (rawGeneratedBy.isNotEmpty ? rawGeneratedBy : 'Platform Admin');

    final completed = monthlySnapshot?.metricInt('tasksCompleted') ??
        tasks.where((task) => task.isCompleted).length;
    final overdue = monthlySnapshot?.metricInt('tasksOverdue') ??
        tasks.where((task) => task.isOverdue).length;
    final projectCount = monthlySnapshot?.metricInt('projectCount') ?? projects.length;
    final taskCount = monthlySnapshot?.metricInt('taskCount') ?? tasks.length;
    final memberCount = monthlySnapshot?.metricInt('memberCount') ?? members.length;
    final completion = monthlySnapshot?.metricInt('completionRate') ??
        (tasks.isEmpty ? 0 : (completed * 100 / tasks.length).round());
    final online = members.where((member) => member.isOnline).length;

    final statusCounts = <String, int>{};
    final priorityCounts = <String, int>{};
    for (final task in tasks) {
      statusCounts[task.status.label] = (statusCounts[task.status.label] ?? 0) + 1;
      priorityCounts[task.priority.label] = (priorityCounts[task.priority.label] ?? 0) + 1;
    }

    final reviewed = members.where((member) {
      return member.appraisalScore > 0 ||
          member.appraisalNotes.trim().isNotEmpty ||
          (member.appraisalStatus.trim().isNotEmpty &&
              member.appraisalStatus != 'notReviewed');
    }).toList();
    final averageScore = reviewed.isEmpty
        ? 0
        : (reviewed.fold<int>(0, (sum, member) => sum + member.appraisalScore) /
                reviewed.length)
            .round();
    final highRatings =
        reviewed.where((member) => member.appraisalScore >= 80).length;
    final followUps =
        reviewed.where((member) => member.appraisalScore > 0 && member.appraisalScore < 60).length;

    final assignments = tasks.fold<int>(
      0,
      (sum, task) => sum + math.max(1, task.assignedToIds.length),
    );
    final utilizations = members.map((member) {
      final assigned = tasks.where((task) => task.assignedToIds.contains(member.uid)).length;
      final capacity = member.capacityHoursPerWeek <= 0
          ? 40
          : member.capacityHoursPerWeek.toDouble();
      return (assigned * 8 * 100 / capacity).clamp(0, 100).round();
    }).toList();
    final averageUtilization = utilizations.isEmpty
        ? 0
        : (utilizations.reduce((a, b) => a + b) / utilizations.length).round();

    final sortedRiskTasks = tasks
        .where((task) => task.isOverdue || task.priority.index >= 2)
        .toList()
      ..sort((a, b) {
        if (a.isOverdue != b.isOverdue) return a.isOverdue ? -1 : 1;
        return b.priority.index.compareTo(a.priority.index);
      });
    final topRisk = sortedRiskTasks.isEmpty
        ? 'No overdue or critical work is currently visible.'
        : '${sortedRiskTasks.first.title} requires management attention.';

    final bestProject = projects.isEmpty
        ? null
        : (projects.toList()..sort((a, b) => b.progress.compareTo(a.progress))).first;
    final bestSignal = bestProject == null
        ? 'No project delivery signal is available yet.'
        : '${bestProject.name} reached ${bestProject.progress}% completion.';

    final nextAction = overdue > 0
        ? 'Recover overdue work and confirm ownership before the next reporting cut-off.'
        : 'Complete dependency QA and approve the HTML/CSS print export.';

    final executiveSummary = overdue == 0
        ? 'Delivery health is stable for $companyName. The reporting scope contains $projectCount project(s), no overdue work, and $completion% overall completion.'
        : 'Delivery requires attention for $companyName. The reporting scope contains $projectCount project(s), $overdue overdue task(s), and $completion% overall completion.';

    final portfolioForecast = overdue == 0
        ? 'Most visible workstreams are on track. Continue dependency QA and protect release capacity before the end of the reporting period.'
        : '$overdue overdue task(s) may affect delivery confidence. Rebalance capacity and close dependency blockers before the next milestone.';

    final criticalNames = sortedRiskTasks.take(3).map((task) => task.title).toList();
    final criticalChain = criticalNames.isEmpty
        ? 'No critical dependency chain is visible. Add predecessor task IDs to generate a production critical path.'
        : '${criticalNames.join(' -> ')}. Delays in this chain can move the release milestone.';

    final strongest = members.isEmpty
        ? 'No scored employee performance is available.'
        : (members.toList()
              ..sort((a, b) => b.appraisalScore.compareTo(a.appraisalScore)))
            .first;
    final strongestDelivery = strongest is Member && strongest.appraisalScore > 0
        ? '${strongest.displayName} shows the strongest visible appraisal score at ${strongest.appraisalScore}%.'
        : 'Delivery leadership should be confirmed after the appraisal cycle is completed.';

    final coachingMember = members.isEmpty
        ? null
        : (members.toList()
              ..sort((a, b) => a.appraisalScore.compareTo(b.appraisalScore)))
            .first;
    final coachingFocus = coachingMember == null || coachingMember.appraisalScore == 0
        ? 'Protect QA and review capacity during release weeks to avoid approval bottlenecks.'
        : '${coachingMember.displayName} should receive coaching support based on the current appraisal evidence.';

    final weekly = _weeklyThroughput(tasks);
    final appraisalTrend = _appraisalTrend(averageScore);

    return _HtmlReportData(
      report: report,
      projects: List<Project>.unmodifiable(projects),
      tasks: List<ProjectTask>.unmodifiable(tasks),
      members: List<Member>.unmodifiable(members),
      companyName: companyName,
      generatedBy: generatedBy,
      monthLabel: _monthLabel(report.monthId.isEmpty ? report.period : report.monthId),
      scopeLabel: report.projectScope == 'project'
          ? (report.metrics['projectName']?.toString().trim().isNotEmpty == true
              ? report.metrics['projectName'].toString()
              : 'Selected Project')
          : 'All Projects',
      projectCount: projectCount,
      taskCount: taskCount,
      memberCount: memberCount,
      completedTasks: completed,
      overdueTasks: overdue,
      overallCompletion: completion.clamp(0, 100).toInt(),
      onlineMembers: online,
      totalAssignments: assignments,
      averageUtilization: averageUtilization,
      reviewedMembers: reviewed.length,
      averageAppraisalScore: averageScore.clamp(0, 100).toInt(),
      highRatingMembers: highRatings,
      followUpMembers: followUps,
      executiveSummary: executiveSummary,
      topRisk: topRisk,
      bestSignal: bestSignal,
      nextAction: nextAction,
      portfolioForecast: portfolioForecast,
      criticalChain: criticalChain,
      strongestDelivery: strongestDelivery,
      coachingFocus: coachingFocus,
      taskStatusCounts: statusCounts,
      taskPriorityCounts: priorityCounts,
      weeklyThroughput: weekly,
      appraisalTrend: appraisalTrend,
      notificationReadiness: <String, int>{
        'foreground': _metricInt(report.metrics, 'fcmForegroundReadiness'),
        'background': _metricInt(report.metrics, 'fcmBackgroundReadiness'),
        'terminated': _metricInt(report.metrics, 'fcmTerminatedReadiness'),
        'acceptAction': _metricInt(report.metrics, 'fcmAcceptActionReadiness'),
      },
    );
  }

  String projectName(String projectId) {
    for (final project in projects) {
      if (project.projectId == projectId) return project.name;
    }
    return projectId.trim().isEmpty ? 'No project' : projectId;
  }

  String assigneeNames(List<String> memberIds) {
    if (memberIds.isEmpty) return 'Unassigned';
    final names = <String>[];
    for (final memberId in memberIds) {
      Member? match;
      for (final member in members) {
        if (member.uid == memberId) {
          match = member;
          break;
        }
      }
      names.add(match?.displayName ?? memberId);
    }
    return names.join(', ');
  }

  int assignedTaskCount(String memberId) =>
      tasks.where((task) => task.assignedToIds.contains(memberId)).length;

  int completedTaskCount(String memberId) => tasks
      .where((task) => task.isCompleted && task.assignedToIds.contains(memberId))
      .length;

  int memberUtilization(Member member) {
    final assigned = assignedTaskCount(member.uid);
    final capacity = member.capacityHoursPerWeek <= 0
        ? 40
        : member.capacityHoursPerWeek.toDouble();
    return (assigned * 8 * 100 / capacity).clamp(0, 100).round();
  }

  int taskProgress(ProjectTask task) {
    if (task.progressPercent != null) {
      return task.progressPercent!.clamp(0, 100).toInt();
    }
    if (task.isCompleted) return 100;
    final token = task.status.value.toLowerCase();
    if (token.contains('testing')) return 85;
    if (token.contains('review')) return 72;
    if (token.contains('progress')) return 55;
    if (token.contains('todo')) return 20;
    return 8;
  }

  String ratingLabel(int score) {
    if (score >= 80) return 'High';
    if (score >= 60) return 'Medium';
    if (score > 0) return 'Follow-up';
    return 'Not reviewed';
  }

  static int _metricInt(Map<String, dynamic> map, String key) {
    final value = map[key];
    if (value is int) return value.clamp(0, 100).toInt();
    if (value is num) return value.round().clamp(0, 100).toInt();
    return int.tryParse(value?.toString() ?? '')?.clamp(0, 100).toInt() ?? 0;
  }

  static List<int> _weeklyThroughput(List<ProjectTask> tasks) {
    final output = List<int>.filled(7, 0);
    for (final task in tasks.where((task) => task.completedAt != null)) {
      final completedAt = task.completedAt!;
      output[(completedAt.day - 1).clamp(0, 27) ~/ 4] += 1;
    }
    if (output.every((value) => value == 0)) {
      var running = 0;
      for (var index = 0; index < output.length; index += 1) {
        running += tasks.length ~/ math.max(1, output.length);
        output[index] = running;
      }
    }
    return output;
  }

  static List<int> _appraisalTrend(int current) {
    if (current <= 0) return const <int>[0, 0, 0, 0, 0, 0];
    return <int>[
      (current - 18).clamp(0, 100).toInt(),
      (current - 13).clamp(0, 100).toInt(),
      (current - 10).clamp(0, 100).toInt(),
      (current - 6).clamp(0, 100).toInt(),
      (current - 2).clamp(0, 100).toInt(),
      current,
    ];
  }

  static String _monthLabel(String value) {
    const months = <String>[
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December',
    ];
    final normalized = value.trim();
    final match = RegExp(r'^(\d{4})[-/](\d{1,2})').firstMatch(normalized);
    if (match != null) {
      final year = int.tryParse(match.group(1) ?? '');
      final month = int.tryParse(match.group(2) ?? '');
      if (year != null && month != null && month >= 1 && month <= 12) {
        return '${months[month - 1]} $year';
      }
    }
    return normalized.isEmpty ? 'Reporting Period' : normalized;
  }

  static String _short(DateTime value) {
    const months = <String>[
      'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
    ];
    return '${value.day.toString().padLeft(2, '0')} ${months[value.month - 1]}';
  }
}