// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnhRkFqbAU6RvBF0okym8T95Ooh7oG-6E',
    appId: '1:1051281746131:web:decb710a96982193460c26',
    messagingSenderId: '1051281746131',
    projectId: 'project-management-dashb-aa77a',
    authDomain: 'project-management-dashb-aa77a.firebaseapp.com',
    storageBucket: 'project-management-dashb-aa77a.firebasestorage.app',
    measurementId: 'G-EJHXR1WNSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2IOr5Q6QakF8bv4a3F1p3lnke7JRac4U',
    appId: '1:1051281746131:android:c2bcb45beddb46d2460c26',
    messagingSenderId: '1051281746131',
    projectId: 'project-management-dashb-aa77a',
    storageBucket: 'project-management-dashb-aa77a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKkCrumabmYTwu90MT4hrXvS_E7Wa-0HU',
    appId: '1:1051281746131:ios:ed89eea1aef75c1f460c26',
    messagingSenderId: '1051281746131',
    projectId: 'project-management-dashb-aa77a',
    storageBucket: 'project-management-dashb-aa77a.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKkCrumabmYTwu90MT4hrXvS_E7Wa-0HU',
    appId: '1:1051281746131:ios:ed89eea1aef75c1f460c26',
    messagingSenderId: '1051281746131',
    projectId: 'project-management-dashb-aa77a',
    storageBucket: 'project-management-dashb-aa77a.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnhRkFqbAU6RvBF0okym8T95Ooh7oG-6E',
    appId: '1:1051281746131:web:48f6832e07e2ae09460c26',
    messagingSenderId: '1051281746131',
    projectId: 'project-management-dashb-aa77a',
    authDomain: 'project-management-dashb-aa77a.firebaseapp.com',
    storageBucket: 'project-management-dashb-aa77a.firebasestorage.app',
    measurementId: 'G-9S5DX6Z4JW',
  );
}
